language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

matrix:

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - php composer.phar install -d examples/laravel-5

script:
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - vendor/bin/phpunit
  - (cd examples/laravel-5 && vendor/bin/phpunit)
