name: PHP7 Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          composer install -d examples/laravel-5.x --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: |
          vendor/bin/phpunit
          cd examples/laravel-5.x && vendor/bin/phpunit
